name: mlmpfr CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
        ocaml-compiler: [4.14.0, 5.0.0, 5.2.0]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      # setup-ocaml automatically install mlmpfr dependencies (i.e.: gmp/mpfr)
      # rely on dune configurator for C and link flags

      - name: Build and test mlmpfr
        run: |
          opam install . --deps-only --with-doc --with-test
          opam exec -- dune build @install --profile dev
          opam exec -- dune build @runtest --profile dev --verbose
          opam exec -- dune build @doc
          opam exec -- dune install
          opam exec -- dune exec examples/example.exe
